markdown: redcarpet
highlighter: null
permalink: /:title

url:
baseurl:

redcarpet:
  extensions: [strikethrough, tables]

sass:
  sass_dir: public/css
  style: :compressed

# Disqus comments
comments :
  provider : disqus
  disqus :
    short_name : kwareblog


